import {
  createEmptyTemplate,
  DEFAULT_EMBASSY_LOGO,
  DEFAULT_SALAAM_LOGO,
  type VisaTemplate,
} from './types';

const defaultLogos = {
  salaamLogoUrl: DEFAULT_SALAAM_LOGO,
  embassyLogoUrl: DEFAULT_EMBASSY_LOGO,
};

export const MOCK_TEMPLATES: VisaTemplate[] = [
  createEmptyTemplate({
    id: 'tpl-tourist-std',
    name: 'Standard Tourist Visa',
    visaType: 'tourist',
    status: 'active',
    isDefault: true,
    updatedAt: '2026-07-08',
    accentColor: '#1B4D45',
    header: {
      title: 'Islamic Emirate of Afghanistan — Tourist Visa',
      addressLine: 'Salaam Afghanistan · Consular Processing Center',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
  createEmptyTemplate({
    id: 'tpl-business-std',
    name: 'Business Entry Permit',
    visaType: 'business',
    status: 'active',
    isDefault: false,
    updatedAt: '2026-07-02',
    accentColor: '#0B3D2E',
    header: {
      title: 'Islamic Emirate of Afghanistan — Business Visa',
      addressLine: 'Ministry of Foreign Affairs · Commercial Affairs Desk',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
  createEmptyTemplate({
    id: 'tpl-student-draft',
    name: 'Student Visa Draft',
    visaType: 'student',
    status: 'draft',
    isDefault: false,
    updatedAt: '2026-06-28',
    accentColor: '#C4A35A',
    header: {
      title: 'Islamic Emirate of Afghanistan — Student Visa',
      addressLine: 'Education & Cultural Affairs · Kabul',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
  createEmptyTemplate({
    id: 'tpl-transit',
    name: 'Airport Transit Letter',
    visaType: 'transit',
    status: 'active',
    isDefault: false,
    updatedAt: '2026-06-15',
    accentColor: '#E8B84A',
    header: {
      title: 'Transit Authorization',
      addressLine: 'Border & Airport Control · Kabul International',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
  createEmptyTemplate({
    id: 'tpl-tourist-premium',
    name: 'Premium Tourist Certificate',
    visaType: 'tourist',
    status: 'draft',
    isDefault: false,
    updatedAt: '2026-07-10',
    accentColor: '#1B4D45',
    fontSize: 14,
    header: {
      title: 'Islamic Emirate of Afghanistan — Premium Tourist Visa',
      addressLine: 'Salaam Afghanistan · Priority Consular Lane',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
  createEmptyTemplate({
    id: 'tpl-business-embassy',
    name: 'Embassy Business Template',
    visaType: 'business',
    status: 'active',
    isDefault: false,
    updatedAt: '2026-05-30',
    accentColor: '#0B3D2E',
    header: {
      title: 'Diplomatic Mission — Business Visa',
      addressLine: 'Afghan Embassy Consular Section',
      govLine: 'ISLAMIC EMIRATE OF AFGHANISTAN',
      ministryLine: 'Ministry of Foreign Affairs',
      systemLine: 'Salaam Afghanistan — Electronic Visa System',
      sectionTitle: 'eVISA Holder Information',
      ...defaultLogos,
    },
  }),
];
