const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const Application = require('../models/Application');
const IssuedVisa = require('../models/IssuedVisa');
const VisaTemplate = require('../models/VisaTemplate');
const ApplicationDocument = require('../models/ApplicationDocument');
const PlatformSettings = require('../models/PlatformSettings');
const { APPLICATION_STATUSES } = require('../config/statusWorkflow');
const { ApiError } = require('../middleware/error');
const { generateVisaNumber } = require('../utils/helpers');
const { uploadRoot } = require('../middleware/upload');
const { changeApplicationStatus } = require('./statusService');
const { notifyApplicant } = require('./emailService');

async function generateVisaPdf({ application, template, visaNumber, outputPath }) {
  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: [template.pageWidth || 595, template.pageHeight || 842],
      margin: 40,
    });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    doc.fontSize(20).text('Islamic Emirate of Afghanistan', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(16).text('Visa Document', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Visa Number: ${visaNumber}`);
    doc.text(`Reference: ${application.referenceId}`);
    doc.text(`Name: ${application.personal?.fullName || application.passport?.fullName || ''}`);
    doc.text(`Passport: ${application.passport?.passportNumber || ''}`);
    doc.text(`Nationality: ${application.personal?.nationality || application.passport?.nationality || ''}`);
    doc.text(`Visa Type: ${application.visaTypeCode}`);
    doc.text(`Entries: ${application.channel === 'evisa' ? 'single' : 'as authorized'}`);
    doc.text(`Issued: ${new Date().toISOString().slice(0, 10)}`);
    if (application.travel?.intendedEntryDate) {
      doc.text(`Valid from: ${new Date(application.travel.intendedEntryDate).toISOString().slice(0, 10)}`);
    }
    const stay = application.travel?.stayDurationDays || 30;
    const validUntil = new Date(application.travel?.intendedEntryDate || Date.now());
    validUntil.setDate(validUntil.getDate() + stay);
    doc.text(`Valid until: ${validUntil.toISOString().slice(0, 10)}`);
    doc.moveDown();
    doc.text('This document was generated by Salaam Afghanistan.');
    if (template.includeQr) {
      doc.moveDown();
      doc.text(`QR Payload: ${visaNumber}|${application.referenceId}`);
    }

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

async function issueVisaForApplication({ applicationId, staff, embassyStaff, force = false }) {
  if (!staff && !embassyStaff) {
    throw new ApiError(500, 'Visa issuance requires an actor');
  }

  const application = await Application.findById(applicationId);
  if (!application) throw new ApiError(404, 'Application not found');

  if (application.status === APPLICATION_STATUSES.VISA_ISSUED && !force) {
    const existing = await IssuedVisa.findOne({ application: application._id });
    if (existing) return existing;
  }

  if (
    application.status !== APPLICATION_STATUSES.APPROVED &&
    application.status !== APPLICATION_STATUSES.VISA_ISSUED
  ) {
    throw new ApiError(400, 'Visa can only be issued for approved applications');
  }

  const settings = await PlatformSettings.findOne({ key: 'default' }).lean();
  let template = await VisaTemplate.findOne({ isDefault: true, isActive: true });
  if (!template) {
    template = await VisaTemplate.findOne({ isActive: true });
  }
  if (!template) {
    template = await VisaTemplate.create({
      code: 'default_visa',
      name: 'Default Visa Template',
      isDefault: true,
      placeholders: [],
    });
  }

  const actorId = (staff || embassyStaff)._id;
  const visaNumber = generateVisaNumber();
  const fileName = `${visaNumber}.pdf`;
  const storagePath = path.join('visas', fileName);
  const absolute = path.join(uploadRoot, storagePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });

  await generateVisaPdf({ application, template, visaNumber, outputPath: absolute });

  const validFrom = application.travel?.intendedEntryDate || new Date();
  const stay = application.travel?.stayDurationDays || 30;
  const validUntil = new Date(validFrom);
  validUntil.setDate(validUntil.getDate() + stay);

  const docRecord = await ApplicationDocument.create({
    application: application._id,
    key: 'issued_visa',
    label: 'Issued Visa',
    originalName: fileName,
    mimeType: 'application/pdf',
    size: fs.statSync(absolute).size,
    storageProvider: 'local',
    storagePath,
    uploadedByType: staff ? 'staff' : 'system',
    uploadedBy: actorId,
    category: 'visa_document',
    visibleToApplicant: true,
    deliveredAt: new Date(),
  });

  const issued = await IssuedVisa.findOneAndUpdate(
    { application: application._id },
    {
      $set: {
        referenceId: application.referenceId,
        visaNumber,
        visaTypeCode: application.visaTypeCode,
        applicantName: application.personal?.fullName || application.passport?.fullName || 'Unknown',
        nationality: application.personal?.nationality || application.passport?.nationality,
        passportNumber: application.passport?.passportNumber,
        embassy: application.embassy,
        template: template._id,
        validFrom,
        validUntil,
        entries: 'single',
        document: docRecord._id,
        storagePath,
        qrPayload: `${visaNumber}|${application.referenceId}`,
        issuedBy: staff ? staff._id : undefined,
        issuedByEmbassyStaff: embassyStaff ? embassyStaff._id : undefined,
        issuedAt: new Date(),
      },
    },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );

  if (application.status === APPLICATION_STATUSES.APPROVED) {
    await changeApplicationStatus({
      application,
      toStatus: APPLICATION_STATUSES.VISA_ISSUED,
      staff,
      embassyStaff,
      note: `Visa issued: ${visaNumber}`,
    });
  }

  if (application.applicant && application.personal?.email) {
    if (settings?.notifications?.visaIssuedEmails !== false) {
      await notifyApplicant({
        applicantId: application.applicant,
        email: application.personal.email,
        type: 'visa_issued',
        title: `Visa issued for ${application.referenceId}`,
        body: `Your visa ${visaNumber} has been issued and is available in your profile.`,
        applicationId: application._id,
        templateCode: 'visa_issued',
        vars: {
          referenceId: application.referenceId,
          visaNumber,
          fullName: application.personal.fullName || '',
        },
      });
    }
  }

  return issued;
}

module.exports = {
  issueVisaForApplication,
  generateVisaPdf,
};
