/**
 * PRD 8.2 — Application status workflow (configurable transitions)
 */

const APPLICATION_STATUSES = Object.freeze({
  DRAFT: 'draft',
  PENDING: 'pending',
  DOCUMENTS_REQUIRED: 'documents_required',
  SENT_TO_EMBASSY: 'sent_to_embassy',
  UNDER_EMBASSY_REVIEW: 'under_embassy_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  VISA_ISSUED: 'visa_issued',
  CLOSED: 'closed',
  ARCHIVED: 'archived',
});

const STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.DRAFT]: [APPLICATION_STATUSES.PENDING],
  [APPLICATION_STATUSES.PENDING]: [
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
    APPLICATION_STATUSES.SENT_TO_EMBASSY,
    APPLICATION_STATUSES.REJECTED,
  ],
  [APPLICATION_STATUSES.DOCUMENTS_REQUIRED]: [
    APPLICATION_STATUSES.PENDING,
    APPLICATION_STATUSES.REJECTED,
  ],
  [APPLICATION_STATUSES.SENT_TO_EMBASSY]: [APPLICATION_STATUSES.UNDER_EMBASSY_REVIEW],
  [APPLICATION_STATUSES.UNDER_EMBASSY_REVIEW]: [
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
  ],
  [APPLICATION_STATUSES.APPROVED]: [APPLICATION_STATUSES.VISA_ISSUED],
  [APPLICATION_STATUSES.REJECTED]: [APPLICATION_STATUSES.CLOSED],
  [APPLICATION_STATUSES.VISA_ISSUED]: [
    APPLICATION_STATUSES.CLOSED,
    APPLICATION_STATUSES.ARCHIVED,
  ],
  [APPLICATION_STATUSES.CLOSED]: [APPLICATION_STATUSES.ARCHIVED],
  [APPLICATION_STATUSES.ARCHIVED]: [],
});

/** Embassy panel decisioning (PRD 9.2) */
const EMBASSY_STATUS_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.SENT_TO_EMBASSY]: [
    APPLICATION_STATUSES.UNDER_EMBASSY_REVIEW,
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
  ],
  [APPLICATION_STATUSES.UNDER_EMBASSY_REVIEW]: [
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.DOCUMENTS_REQUIRED,
  ],
  // Auto/manual visa generation after embassy approval
  [APPLICATION_STATUSES.APPROVED]: [APPLICATION_STATUSES.VISA_ISSUED],
});

/** Receptionist may only move draft/intake into pending */
const RECEPTIONIST_ALLOWED_TRANSITIONS = Object.freeze({
  [APPLICATION_STATUSES.DRAFT]: [APPLICATION_STATUSES.PENDING],
});

function canTransition(from, to, { isReceptionist = false, isEmbassy = false } = {}) {
  const map = isEmbassy
    ? EMBASSY_STATUS_TRANSITIONS
    : isReceptionist
      ? RECEPTIONIST_ALLOWED_TRANSITIONS
      : STATUS_TRANSITIONS;
  return (map[from] || []).includes(to);
}

function getAllowedNextStatuses(from, { isReceptionist = false, isEmbassy = false } = {}) {
  const map = isEmbassy
    ? EMBASSY_STATUS_TRANSITIONS
    : isReceptionist
      ? RECEPTIONIST_ALLOWED_TRANSITIONS
      : STATUS_TRANSITIONS;
  return map[from] || [];
}

module.exports = {
  APPLICATION_STATUSES,
  STATUS_TRANSITIONS,
  EMBASSY_STATUS_TRANSITIONS,
  RECEPTIONIST_ALLOWED_TRANSITIONS,
  canTransition,
  getAllowedNextStatuses,
};
